content_css: 'assets/application.css'
width: '530'
height: '400'
theme: 'advanced'
inlinepopups_skin : 'somos-inlinepopups'
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: ''
theme_advanced_buttons1: 'undo,redo,|,bold,italic,|,link,unlink,|,numlist,bullist'
theme_advanced_buttons2: ''
theme_advanced_buttons3: ''
theme_advanced_buttons4: ''
plugins: 'inlinepopups'
